USE QLSV_TH01
GO
--CÂU 1
SELECT TENSV
FROM SVIEN
WHERE MAKHOA='TOAN'
GO

--CÂU 2
SELECT TENMH,TINCHI
FROM MHOC
GO

--CÂU 3
SELECT MASV,MAHP,DIEM
FROM KQUA
WHERE MASV='K26.0008'
GO

--CÂU 4
SELECT MASV,MAMH,DIEM
FROM KQUA JOIN HPHAN ON KQUA.MAHP=HPHAN.MAHP
WHERE DIEM>7
GO

--CÂU 5
SELECT TENSV,SVIEN.MAKHOA,TENMH
FROM SVIEN JOIN MHOC ON SVIEN.MAKHOA=MHOC.MAKHOA
WHERE TENMH=N'Toán rời rạc'
GO

--CÂU 6
SELECT TENSV,TENMH,DIEM
FROM SVIEN,MHOC,KQUA,HPHAN
WHERE SVIEN.MASV=KQUA.MASV AND KQUA.MAHP=HPHAN.MAHP AND HPHAN.MAMH=MHOC.MAMH AND HOCKY=1 AND HPHAN.NAM=1996
GO

--CÂU 7
SELECT MH2.MAMH, MH2.TENMH
FROM MHOC MH1, MHOC MH2, DKIEN DK
WHERE MH1.MAMH=DK.MAMH AND MH2.MAMH=DK.MAMH_TRUOC AND MH1.TENMH=N'CƠ SỞ DỮ LIỆU'
GO

--CÂU 8
SELECT MH1.MAMH, MH1.TENMH
FROM MHOC MH, DKIEN DK, MHOC MH1
WHERE MH.MAMH=DK.MAMH_TRUOC AND MH.TENMH=N'CƠ SỞ DỮ LIỆU' AND DK.MAMH=MH1.MAMH
GO

--CÂU 9
SELECT MH.TENMH N'Môn học', MH.TINCHI N'Tín chỉ',MH1.TENMH N'Môn học trước'
FROM MHOC MH, DKIEN DK,MHOC MH1
WHERE MH.MAMH=DK.MAMH AND MH.TINCHI<=4 AND MH1.MAMH=DK.MAMH_TRUOC
GO

--CÂU 10
SELECT SV.MASV, TENSV, DIEM
FROM SVIEN SV, KQUA KQ, HPHAN HP,MHOC MH
WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND HP.MAMH=MH.MAMH AND HP.NAM=1996 AND HOCKY=1 AND TENMH=N'CƠ SỞ DỮ LIỆU'
ORDER BY DIEM ASC
GO

--CÂU 11
SELECT KQ.MAHP, COUNT(KQ.MAHP) N'Số lượng SV đký'
FROM HPHAN HP, KQUA KQ
WHERE HP.MAHP=KQ.MAHP
GROUP BY KQ.MAHP
GO

--CÂU 12
SELECT TENSV N'Họ tên',HOCKY N'Học kỳ', HP.NAM N'Năm', AVG(DIEM) N'Điểm'
FROM SVIEN SV,HPHAN HP, KQUA KQ
GROUP BY TENSV,HOCKY, HP.NAM
ORDER BY TENSV ASC, HP.NAM ASC
GO

--CÂU 13
SELECT TENSV,MAHP,DIEM
FROM SVIEN SV JOIN KQUA KQ ON SV.MASV=KQ.MASV 
WHERE DIEM>= ALL
			(SELECT DIEM
			FROM SVIEN SV JOIN KQUA KQ ON SV.MASV=KQ.MASV )
GO

--CÂU 14
SELECT SV.MASV, TENSV,KQ.MAHP,DIEM
FROM SVIEN SV, KQUA KQ, HPHAN HP, MHOC MH
WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND HP.MAMH=MH.MAMH AND TENMH=N'CƠ SỞ DỮ LIỆU' AND HP.NAM=1 AND HP.NAM=1996 AND DIEM>= ALL
			(SELECT DIEM
			FROM SVIEN SV, KQUA KQ, HPHAN HP, MHOC MH
			WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND HP.MAMH=MH.MAMH AND TENMH=N'CƠ SỞ DỮ LIỆU' AND HP.NAM=1 AND HP.NAM=1996)
GO

--CÂU 15
SELECT SV.MASV, TENSV N'Họ tên', AVG(DIEM) ĐTB
FROM SVIEN SV, KQUA KQ, HPHAN HP
WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND HOCKY=1 AND HP.NAM=1996
GROUP BY SV.MASV, TENSV
HAVING AVG(DIEM)>=ALL
				(SELECT AVG(DIEM)
				FROM KQUA KQ JOIN HPHAN HP ON KQ.MAHP=HP.MAHP
				WHERE NAM=1996 AND HOCKY=1
				GROUP BY MASV)
GO

--CÂU 16: CHƯA XONG
SELECT TOP 10 SV.MASV, TENSV N'Họ tên', AVG(DIEM) ĐTB
FROM SVIEN SV, KQUA KQ, HPHAN HP,MHOC MH
WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND HOCKY=1 AND HP.NAM=1996 AND MH.MAMH=HP.MAMH AND TENMH=N'CƠ SỞ DỮ LIỆU'
GROUP BY SV.MASV, TENSV
ORDER BY AVG(DIEM) ASC
GO

--CÂU 17
SELECT MASV, TENSV
FROM SVIEN
EXCEPT
SELECT SV.MASV, TENSV
FROM SVIEN SV, KQUA KQ, HPHAN HP, MHOC MH
WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND HP.MAMH=MH.MAMH AND TENMH=N'TOÁN RỜI RẠC'
GO

--CÂU 18
SELECT MH.MAMH, TENMH,MAHP, HOCKY, NAM
FROM HPHAN HP, MHOC MH,KHOA K
WHERE HP.MAMH=MH.MAMH AND MH.MAKHOA=K.MAKHOA AND TENKHOA=N'TOÁN'
EXCEPT
SELECT MH.MAMH, TENMH,MAHP, HOCKY, NAM
FROM HPHAN HP, MHOC MH,KHOA K
WHERE HP.MAMH=MH.MAMH AND MH.MAKHOA=K.MAKHOA AND TENKHOA=N'TOÁN' AND HOCKY=1 AND NAM=1996
GO

-- CÂU 19
SELECT SV.MASV, TENSV, SV.NAM, TENKHOA, TENMH
FROM SVIEN SV, KQUA KQ,HPHAN HP, MHOC MH,KHOA K
WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND HP.MAMH=MH.MAMH AND MH.MAKHOA=K.MAKHOA AND TENKHOA=N'TOÁN' AND SV.NAM=3
EXCEPT
SELECT SV.MASV, TENSV, SV.NAM, TENKHOA, TENMH
FROM SVIEN SV, KQUA KQ,HPHAN HP, MHOC MH,KHOA K
WHERE SV.MASV=KQ.MASV AND KQ.MAHP=HP.MAHP AND MH.MAMH=HP.MAMH AND MH.MAKHOA=K.MAKHOA AND TENKHOA=N'TOÁN' AND SV.NAM=3 AND TENKHOA=N'TOÁN' AND HOCKY=1 AND HP.NAM=1996 AND TENMH=N'CƠ SỞ DỮ LIỆU'
GO

--CÂU 20
SELECT SV.MASV, TENSV N'Họ tên', COUNT(KQ.MAHP) N'Số học phần'
FROM SVIEN SV, KQUA KQ, HPHAN HP
WHERE SV.MASV=KQ.MASV AND HP.MAHP=KQ.MAHP
GROUP BY SV.MASV, TENSV
HAVING COUNT(KQ.MAHP)>3