USE QLNV

--CÂU 1
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE PHONG='NC'

--CÂU 2
SELECT MANV, HONV, TENLOT, TENNV, PHAI
FROM NHANVIEN
WHERE MLUONG>=3000000

--CÂU 3
SELECT HONV+' '+TENLOT+' '+TENNV N'Họ tên', TENPHONG
FROM NHANVIEN, PHONGBAN
WHERE MLUONG>=2000000 AND MLUONG<=3000000

--CÂU 4
SELECT HONV+' '+TENLOT+' '+TENNV N'Họ tên'
FROM NHANVIEN
WHERE DCHI LIKE '%TpHCM'

--CÂU 5
SELECT NGAYSINH, DCHI
FROM NHANVIEN
WHERE HONV+' '+TENLOT+' '+TENNV=N'ĐINH BÁ TIẾN'

--CÂU 6
SELECT MATN, TENTN, QUANHE
FROM THANNHAN
WHERE MANV='NV001' AND YEAR(GETDATE())-YEAR(NGSINH)>=18

--CÂU 7
SELECT *
FROM NHANVIEN
WHERE PHAI=N'NỮ' AND YEAR(GETDATE())-YEAR(NGAYSINH)>=30

--CÂU 8
SELECT TENPHONG, DIADIEM
FROM PHONGBAN P JOIN DIADIEM_PHG DD ON P.MAPHONG=DD.MAPHG

--CÂU 9
SELECT HONV+' '+TENLOT+' '+TENNV, TENPHONG
FROM NHANVIEN NV JOIN PHONGBAN PB ON NV.PHONG=PB.MAPHONG
WHERE TRPHONG=MANV

--CÂU 10
SELECT TENDA, MADA, DDIEM_DA, MAPHONG, TENPHONG, MAPHG, TRPHONG, NGNC
FROM DEAN DA JOIN PHONGBAN P ON DA.MAPHG=P.MAPHONG

--CÂU 11
SELECT HONV+' '+TENLOT+' '+TENNV N'Họ tên', DCHI
FROM NHANVIEN NV JOIN PHONGBAN P ON NV.PHONG=P.MAPHONG
WHERE TENPHONG=N'NGHIÊN CỨU'

--CÂU 12
SELECT HONV+' '+TENLOT+' '+TENNV N'Họ tên', TENTN, QUANHE
FROM NHANVIEN NV JOIN THANNHAN TN ON NV.MANV=TN.MANV
WHERE NV.PHAI=N'NỮ'

--CÂU 13
SELECT NV.MANV, HONV+' '+TENLOT+' '+TENNV N'Họ và tên', TENDA
FROM NHANVIEN NV, PHONGBAN P, PHANCONG PC, DEAN DA
WHERE NV.PHONG=P.MAPHONG AND NV.MANV=PC.MANV AND DA.MADA=PC.MADA
AND TENPHONG=N'NGHIÊN CỨU' AND THOIGIAN=20 AND TENDA LIKE N'Tin học hoá%'
GO

--CÂU 14
SELECT MADA, MAPHG,HONV+' '+TENLOT+' '+TENNV N'Trưởng phòng',DCHI, NGAYSINH
FROM DEAN DA, PHONGBAN P, NHANVIEN NV
WHERE DDIEM_DA='HANOI'
AND DA.MAPHG=P.MAPHONG AND TRPHONG=MANV

--CÂU 15
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên', NV1.HONV+' '+NV1.TENLOT+' '+NV1.TENNV N'Người quản lý'
FROM NHANVIEN NV JOIN NHANVIEN NV1 ON NV1.MANV=NV.MA_NQL
GO

--CÂU 16
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên', NV1.HONV+' '+NV1.TENLOT+' '+NV1.TENNV N'Trưởng phòng', TENPHONG N'Phòng'
FROM NHANVIEN NV, PHONGBAN P, NHANVIEN NV1
WHERE NV.PHONG=P.MAPHONG AND NV1.MANV=NV.MA_NQL
GO

--CÂU 17
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên',TENDA N'Đề án'
FROM NHANVIEN NV, DEAN DA, PHANCONG PC
WHERE NV.MANV=PC.MANV AND DA.MADA=PC.MADA
GO

--CÂU 18
SELECT TENDA N'Đề án', SUM(THOIGIAN) N'Tổng thời gian'
FROM DEAN DA JOIN PHANCONG PC ON DA.MADA=PC.MADA
GROUP BY TENDA
GO

--CÂU 19
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên', COUNT(MATN) N'Số thân nhân'
FROM NHANVIEN NV JOIN THANNHAN TN ON NV.MANV=TN.MANV
GROUP BY NV.HONV+' '+NV.TENLOT+' '+NV.TENNV
GO

--CÂU 20
SELECT TENPHONG N'Phòng', AVG(MLUONG) N'Trung bình lương'
FROM PHONGBAN P JOIN NHANVIEN NV ON MAPHONG=PHONG
GROUP BY TENPHONG

--CÂU 21
SELECT AVG(MLUONG) N'Lương trung bình của nữ nhân viên'
FROM NHANVIEN
WHERE PHAI=N'NỮ'
GO

--CÂU 22
SELECT TENPHONG N'Phòng', COUNT(MANV) N'Số nhân viên', AVG(MLUONG) N'Trung bình lương'
FROM PHONGBAN P JOIN NHANVIEN NV ON MAPHONG=PHONG
GROUP BY TENPHONG
HAVING AVG(MLUONG)>=3000000

--CÂU 23
/*
1. TÌM ĐỀ ÁN VÀ NHÂN VIÊN CÓ TRƯỞNG PHÒNG LÀM CHUNG MANG HỌ ĐINH
- CÔNG VIỆC
	+ TÌM NGƯỜI TRƯỞNG PHÒNG HỌ ĐINH
	+ TÌM ĐỀ ÁN NGƯỜI TRƯỞNG PHÒNG ĐÓ ĐƯỢC PHÂN CÔNG
	+ TÌM NHỮNG NHÂN VIÊN LÀM ĐỀ ÁN CHUNG VỚI TRƯỞNG PHÒNG
*/ 
SELECT HONV+' '+TENLOT+' '+TENNV N'Nhân viên', MADA
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV
WHERE MADA IN
		(SELECT MADA
		FROM NHANVIEN NV1, NHANVIEN NV2, PHANCONG PC--,PHANCONG PC1,NHANVIEN NV
		WHERE NV1.MA_NQL=NV2.MANV AND NV1.MA_NQL=PC.MANV --AND PC.MADA=PC1.MADA AND NV.MANV=PC1.MADA
		AND NV2.HONV=N'ĐINH')

--CÂU 24
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên',COUNT(MATN) N'Số thân nhân'
FROM NHANVIEN NV JOIN THANNHAN TN ON NV.MANV=TN.MANV
GROUP BY NV.HONV+' '+NV.TENLOT+' '+NV.TENNV
HAVING COUNT(MATN)>=2
GO

--CÂU 25
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên'
FROM NHANVIEN NV 
WHERE NV.MANV NOT IN 
				(SELECT NV.MANV
				FROM NHANVIEN NV JOIN THANNHAN TN ON NV.MANV=TN.MANV)
GO

--CÂU 26
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên',COUNT(MATN) N'Số thân nhân'
FROM NHANVIEN NV JOIN THANNHAN TN ON NV.MANV=TN.MANV
GROUP BY NV.HONV+' '+NV.TENLOT+' '+NV.TENNV
HAVING COUNT(MATN)>=1
GO

--CÂU 27
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên'
FROM NHANVIEN NV, THANNHAN TN
WHERE NV.MANV=TN.MANV
AND NV.MA_NQL NOT IN 
				(SELECT NV.MANV
				FROM NHANVIEN NV JOIN THANNHAN TN ON NV.MANV=TN.MANV)
GO

--CÂU 28
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên',MLUONG
FROM NHANVIEN NV
WHERE MLUONG>ALL
			(SELECT AVG(MLUONG)
			FROM NHANVIEN NV JOIN PHONGBAN P ON PHONG=MAPHONG
			WHERE TENPHONG=N'NGHIÊN CỨU'
			GROUP BY TENPHONG)
GO

--CÂU 29
SELECT TENPHONG,NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Trưởng phòng'
FROM NHANVIEN NV JOIN PHONGBAN P ON PHONG=MAPHONG
WHERE TRPHONG=MANV
AND TENPHONG IN
			(SELECT TENPHONG
			FROM NHANVIEN NV JOIN PHONGBAN P ON PHONG=MAPHONG
			GROUP BY TENPHONG
			HAVING COUNT(MANV)>=ALL
						(SELECT COUNT(MANV)
						FROM NHANVIEN NV JOIN PHONGBAN P ON PHONG=MAPHONG
						GROUP BY TENPHONG))
GO

--CÂU 30
SELECT NV.HONV+' '+NV.TENLOT+' '+NV.TENNV N'Nhân viên',DCHI
FROM NHANVIEN NV,DEAN DA,PHANCONG PC
WHERE NV.MANV=PC.MANV AND DA.MADA=PC.MADA
AND DDIEM_DA='TPHCM'
AND NV.MANV NOT IN
			(SELECT MANV
			FROM NHANVIEN
			WHERE DCHI LIKE N'%TpHCM')

--CÂU 31