CREATE DATABASE QLD
ON
(
NAME='QLD',
FILENAME='F:\CSDL\SQL_DATA\QLD.mdf',
SIZE = 10MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 5MB)
LOG ON
(NAME='QLD_LOG',
FILENAME='F:\CSDL\SQL_DATA\QLD_LOG.ldf',
SIZE = 5MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 2MB)
GO

USE QLD

CREATE TABLE KHOA
(MAKHOA CHAR(2) CONSTRAINT PK_KHOA PRIMARY KEY,
TENKHOA NVARCHAR(20) CONSTRAINT UQ_TK UNIQUE,
DIENTHOAI CHAR(12),
DIACHI NVARCHAR(200))
GO

CREATE TABLE SINHVIEN
(MASV CHAR(6) CONSTRAINT PK_SV PRIMARY KEY,
HO NVARCHAR(25),
TEN NVARCHAR(8),
NGAYSINH DATE,
GIOITINH NVARCHAR(3) DEFAULT N'Nữ',
CONSTRAINT CHK_GT CHECK(GIOITINH IN (N'Nữ', N'Nam')),
MAKHOA CHAR(2)
CONSTRAINT FK_SV_K FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA),
DIENTHOAI VARCHAR(12),
QUEQUAN NVARCHAR(12),
DOITUONG NVARCHAR(4) DEFAULT N'Khác',
CONSTRAINT CHK_DT CHECK(DOITUONG IN (N'TBLS',N'DTVC',N'GDKK',N'KHÁC')))
GO

CREATE TABLE MONHOC
(MAMH CHAR(4) CONSTRAINT PK_MH PRIMARY KEY,
TENMH NVARCHAR(40),
DVHT INT DEFAULT 3,
HOCKY INT)
GO

CREATE TABLE KETQUA
(MASV CHAR(6),
MAMH CHAR(4),
DIEM FLOAT,
KQHOC VARCHAR(1) CONSTRAINT CHK_KQ CHECK(KQHOC IN ('H','Q','C','L')),
CONSTRAINT PK_KQ PRIMARY KEY(MASV, MAMH),
CONSTRAINT FK_KQ_SV FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
CONSTRAINT FK_KQ_MH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH))
GO