USE QLSV

-- 1. TÌM CÁC MÔN HỌC (MAMH, TENMH, TINCHI, MAKHOA, TENKHOA) ĐƯỢC QUẢN LÝ BỞI KHOA THỐNG KÊ TIN HỌC
SELECT MAMH,TENMH,TINCHI, KHOA.MAKHOA, TENKHOA
FROM MONHOC JOIN KHOA ON MONHOC.MAKHOA=KHOA.MAKHOA
WHERE TENKHOA=N'Thống kê tin học'
GO

--2. CHO BIẾT KHOA(MAKHOA, TENKHOA...) QUẢN LÝ HỌC PHẦN CSDL_2111

SELECT KHOA.MAKHOA, TENKHOA,TENMH
FROM HOCPHAN, KHOA, MONHOC
WHERE KHOA.MAKHOA=MONHOC.MAKHOA AND HOCPHAN.MAMH=MONHOC.MAMH AND HOCPHAN.MAHP='CSDL_2111'
GO

-- 3. TÌM NHỮNG SINH VIÊN () ĐÃ HỌC MÔN CSDL

SELECT SINHVIEN.MASV, TEN, TENMH
FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH AND TENMH=N'Cơ sở dữ liệu'
GO

-- MỆNH ĐỀ ORDER BY

-- ORDER BY TT <ASC/DESC>
SELECT * FROM KHOA
--WHERE
ORDER BY NAMTL DESC
GO

-- DISTINCT - LOẠI GIÁ TRỊ TRÙNG
GO

-- PHÉP TOÁN TẬP HỢP
/*
---> DỮ LIỆU PHẢI KHẢ HỢP
- UNION [ALL]: HỢP (or)
- INTERSECT [ALL]: GIAO (and)
- EXCEPT [ALL]: TRỪ (not)
*/
GO

--TRUY VẤN 1 <PHÉP TOÁN TẬP HỢP> TRUY VẤN 2

-- VÍ DỤ: TÌM SINH SINH HỌC CƠ SỞ DỮ LIỆU HOẶC HỌC CƠ SƠ LẬP TRÌNH
SELECT SINHVIEN.MASV, TEN, TENMH
FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH AND (TENMH=N'Cơ sở dữ liệu')
UNION 
SELECT SINHVIEN.MASV, TEN, TENMH
FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH AND (TENMH=N'CƠ SỞ LẬP TRÌNH')
GO

-- TÌM SINH VIÊN CHƯA HỌC CƠ SỞ DỮ LIỆU
SELECT SINHVIEN.MASV, TEN, TENMH
FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH 
EXCEPT
SELECT SINHVIEN.MASV, TEN, TENMH
FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH AND (TENMH=N'Cơ sở dữ liệu')
GO

-- TRUY VẤN LỒNG: CÓ 2 LOẠI (TRUY VẤN LỒNG PHÂN CẤP VÀ TRUY VẤN LỒNG TƯƠNG QUAN)

-- VÍ DỤ: TÌM SINH VIÊN CHƯA HỌC CƠ SỞ DỮ LIỆU

-- 1. TRUY VẤN LỒNG PHÂN CẤP

SELECT SINHVIEN.MASV, TEN, TENMH
FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH 
AND SINHVIEN.MASV NOT IN
	(SELECT SINHVIEN.MASV
	FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
	WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH AND (TENMH=N'Cơ sở dữ liệu')
	)
	GO

-- TRUY VẤN LỒNG TƯƠNG QUAN
SELECT SINHVIEN.MASV, TEN, TENMH
FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH 
AND NOT EXISTS
	(SELECT *
	FROM SINHVIEN, KETQUA, HOCPHAN,MONHOC
	WHERE SINHVIEN.MASV=KETQUA.MASV AND KETQUA.MAHP=HOCPHAN.MAHP AND HOCPHAN.MAMH=MONHOC.MAMH AND (TENMH=N'Cơ sở dữ liệu')
	)
	GO

--========================================================================================================================================
--1. CHO BIẾT ĐIỂM TRUNG BÌNH CỦA TỪNG SV'

SELECT SV.MASV, TEN, AVG(DIEM) N'ĐIỂM TB'
FROM SINHVIEN SV JOIN KETQUA KQ ON SV.MASV=KQ.MASV
GROUP BY SV.MASV, TEN
GO

--2. CHO BIẾT SỐ LƯỢNG SINH VIÊN CỦA MỖI KHOA

SELECT TENKHOA, COUNT(*) N'SỐ LƯỢNG SV'
FROM SINHVIEN SV JOIN KHOA K ON SV.MAKHOA=K.MAKHOA
GROUP BY TENKHOA
GO

--3. CHO BIẾT TỔNG SỐ MÔN HỌC MÀ SINH VIÊN ĐÃ HỌC

SELECT SV.MASV, TEN, COUNT(MH.MAMH) N'SỐ LƯỢNG MÔN HỌC'
FROM SINHVIEN SV, KETQUA KQ, HOCPHAN HP, MONHOC MH
WHERE SV.MASV=KQ.MASV AND HP.MAHP=KQ.MAHP AND HP.MAMH=MH.MAMH
GROUP BY SV.MASV, TEN
GO

--4. TÌM SINH VIÊN CÓ ĐIỂM TB >=7

SELECT SV.MASV, TEN, AVG(DIEM) N'ĐIỂM TB'
FROM SINHVIEN SV JOIN KETQUA KQ ON SV.MASV=KQ.MASV
GROUP BY SV.MASV, TEN
HAVING AVG(DIEM)>=7
GO

--5. TÌM KHOA CÓ SỐ LƯỢNG SINH VIÊN >=3
SELECT TENKHOA, COUNT(*) N'SỐ LƯỢNG SV'
FROM SINHVIEN SV JOIN KHOA K ON SV.MAKHOA=K.MAKHOA
GROUP BY TENKHOA
HAVING COUNT(*)>=3
GO

--6. TÌM NHỮNG SINH VIÊN CÓ ĐIỂM TRUNG BÌNH = ĐIỂM TRUNG BÌNH CỦA SINH VIÊN CÓ TÊN 'ĐẬU QUANG ÁNH'

SELECT SV.MASV, TEN, AVG(DIEM) N'ĐIỂM TB'
FROM SINHVIEN SV JOIN KETQUA KQ ON SV.MASV=KQ.MASV
WHERE TEN!=N'ĐẬU QUANG ÁNH'
GROUP BY SV.MASV, TEN
HAVING AVG(DIEM)=
		(SELECT AVG(DIEM)
		FROM SINHVIEN SV JOIN KETQUA KQ ON SV.MASV=KQ.MASV
		WHERE TEN=N'ĐẬU QUANG ÁNH'
		GROUP BY TEN)


--6. TÌM NHỮNG SINH VIÊN CÓ ĐIỂM TRUNG BÌNH CAO NHẤT

SELECT SV.MASV, TEN, AVG(DIEM) N'ĐIỂM TB'
FROM SINHVIEN SV JOIN KETQUA KQ ON SV.MASV=KQ.MASV
GROUP BY SV.MASV, TEN
HAVING AVG(DIEM)>=ALL
		(SELECT AVG(DIEM)
		FROM KETQUA KQ
		GROUP BY MASV)

--7. TÌM NHỮNG SINH VIÊN CÓ ĐIỂM TRUNG BÌNH THẤP NHẤT

SELECT SV.MASV, TEN, AVG(DIEM) N'ĐIỂM TB'
FROM SINHVIEN SV JOIN KETQUA KQ ON SV.MASV=KQ.MASV
GROUP BY SV.MASV, TEN
HAVING AVG(DIEM)<=ALL
		(SELECT AVG(DIEM)
		FROM KETQUA KQ
		GROUP BY MASV)

--8. CHO BIẾT NHỮNG SINH VIÊN ĐÃ HỌC TẤT CẢ CÁC MÔN CỦA KHOA THỐNG KÊ TIN HỌC

SELECT SV.MASV, TEN, COUNT(MH.MAMH) 'SỐ LƯỢNG MH'
FROM SINHVIEN SV, KETQUA KQ, HOCPHAN HP, MONHOC MH, KHOA K
WHERE SV.MASV=KQ.MASV AND HP.MAHP=KQ.MAHP AND HP.MAMH=MH.MAMH AND MH.MAKHOA=K.MAKHOA
	AND TENKHOA=N'THỐNG KÊ TIN HỌC'
GROUP BY SV.MASV, TEN
HAVING COUNT(MH.MAMH)=
				(SELECT COUNT(MAMH)
				FROM MONHOC MH JOIN KHOA K ON MH.MAKHOA=K.MAKHOA
				WHERE TENKHOA=N'THỐNG KÊ TIN HỌC'
				GROUP BY K.MAKHOA) 

USE QLNV
--1. CHO BIẾT MỨC LƯƠNG TB CỦA PHÒNG NGHIÊN CỨU
SELECT TENPHONG N'Phòng', AVG(MLUONG) N'Trung bình lương'
FROM PHONGBAN P JOIN NHANVIEN NV ON MAPHONG=PHONG
WHERE TENPHONG=N'NGHIÊN CỨU'
GROUP BY TENPHONG
--2. PHÒNG BAN NÀO CÓ MỨC LƯƠNG CAO HƠN MỨC LƯƠNG TB CỦA PHÒNG NGHIÊN CỨU
SELECT TENPHONG, AVG(MLUONG) 'LƯƠNG TB'
FROM NHANVIEN NV, PHONGBAN PB
WHERE PB.MAPHONG=NV.PHONG
GROUP BY TENPHONG 
HAVING AVG(MLUONG) >
	(SELECT avg(mluong)
	FROM PHONGBAN PB, NHANVIEN NV
	WHERE PB.MAPHONG=NV.PHONG AND TENPHONG=N'NGHIÊN CỨU')
--3. TÌM PHÒNG BAN CÓ MLTB CAO NHẤT
--4. TÌM PHÒNG BAN CÓ MLTB>=5TR
--5. TIM NHÂN VIÊN THAM GIA TẤT CẢ CÁC ĐỀ ÁN CỦA PHÒNG NGHIÊN CỨU